// Code generated by gowsdl DO NOT EDIT.

package service

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type TCKimlikNoDogrula struct {
	XMLName xml.Name `xml:"http://tckimlik.nvi.gov.tr/WS TCKimlikNoDogrula"`

	TCKimlikNo int64 `xml:"TCKimlikNo,omitempty" json:"TCKimlikNo,omitempty"`

	Ad string `xml:"Ad,omitempty" json:"Ad,omitempty"`

	Soyad string `xml:"Soyad,omitempty" json:"Soyad,omitempty"`

	DogumYili int32 `xml:"DogumYili,omitempty" json:"DogumYili,omitempty"`
}

type TCKimlikNoDogrulaResponse struct {
	XMLName xml.Name `xml:"http://tckimlik.nvi.gov.tr/WS TCKimlikNoDogrulaResponse"`

	TCKimlikNoDogrulaResult bool `xml:"TCKimlikNoDogrulaResult,omitempty" json:"TCKimlikNoDogrulaResult,omitempty"`
}

type KPSPublicSoap interface {
	TCKimlikNoDogrula(request *TCKimlikNoDogrula) (*TCKimlikNoDogrulaResponse, error)

	TCKimlikNoDogrulaContext(ctx context.Context, request *TCKimlikNoDogrula) (*TCKimlikNoDogrulaResponse, error)
}

type kPSPublicSoap struct {
	client *soap.Client
}

func NewKPSPublicSoap(client *soap.Client) KPSPublicSoap {
	return &kPSPublicSoap{
		client: client,
	}
}

func (service *kPSPublicSoap) TCKimlikNoDogrulaContext(ctx context.Context, request *TCKimlikNoDogrula) (*TCKimlikNoDogrulaResponse, error) {
	response := new(TCKimlikNoDogrulaResponse)
	err := service.client.CallContext(ctx, "http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *kPSPublicSoap) TCKimlikNoDogrula(request *TCKimlikNoDogrula) (*TCKimlikNoDogrulaResponse, error) {
	return service.TCKimlikNoDogrulaContext(
		context.Background(),
		request,
	)
}
